//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Scripts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Komentar
    {
        public int IDKom { get; set; }
        public string Korisnicko_ime { get; set; }
        public System.DateTime Datum { get; set; }
        public string Sadrzaj { get; set; }
        public int Br_plus { get; set; }
        public int Br_minus { get; set; }
    }
}
